name: ESLint

on:
  push:
    branches: [master]
    paths: ['**/.eslint*', '**/*.js']
  pull_request:
    branches: [master]
    paths: ['**/.eslint*', '**/*.js']

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node JS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Development Dependencies
      run: npm install --only=development

    - name: Install ESLint CLI
      run: npm install --global eslint-cli

    - name: Run ESLint
      run: eslint .
